DROP TABLE IF EXISTS address CASCADE;
-- CREATE USERS
CREATE TABLE address  (
  id SERIAL PRIMARY KEY,
  full_Name VARCHAR(255) NOT NULL,
  address_line_1 VARCHAR(255) NOT NULL,
  address_line_2 VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  state_region VARCHAR(255) NOT NULL,
  zip_code VARCHAR(255) NOT NULL,
  country VARCHAR(255) NOT NULL
);